
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] %>
  database: <%= ENV['DB_ENV_MYSQL_DATABASE'] %>
  username: <%= ENV['DB_ENV_MYSQL_USER'] %>
  password: <%= ENV['DB_ENV_MYSQL_PASSWORD'] %>
